<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Hollowcrown</RootNamespace>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Hollowcrown</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\shared\shared.csproj" />
  </ItemGroup>
</Project>
